Heartify/Heartify/Controllers/PersonProfileController.cs
using Heartify.Core.Contracts;
using Heartify.Core.Models.Gender;
using Heartify.Core.Models.PersonProfile;
using Heartify.Core.Models.Relationship;
using Heartify.Infrastructure.Data.Constants;
using Microsoft.AspNetCore.Mvc;
using System.Globalization;
using System.Security.Claims;
using static Heartify.Core.Constants.MessageConstants;
using static Heartify.Infrastructure.Data.Constants.ValidationConstants;

namespace Heartify.Controllers
{
    public class PersonProfileController : BaseController
    {
        private readonly IPersonProfileService personProfile;
        private readonly ISharedService sharedService;

        public PersonProfileController(IPersonProfileService _personProfile, ISharedService _sharedService)
        {
            personProfile = _personProfile;
            sharedService = _sharedService;
        }

        [HttpGet]
        public async Task<IActionResult> CreatePersonProfile()
        {
            if (await sharedService.ExistsByIdAllAsync(User.Id()))
            {
                return RedirectToAction("PersonProfileInfo", "Returner");
            }

            var model = new PersonProfileFormModel();
            model.Genders = await GetGenders();
            model.Relationships = await GetRelationships();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreatePersonProfile(PersonProfileFormModel model)
        {
            DateTime dateOfBirth = DateTime.Now;

            if (!DateTime.TryParseExact(
                model.DateOfBirth,
                ValidationConstants.DateFormat,
                CultureInfo.InvariantCulture,
                DateTimeStyles.None,
                out dateOfBirth))
            {
                ModelState.AddModelError(nameof(model.DateOfBirth), $"Invalid date! Format must be: {ValidationConstants.DateFormat}");
            }

            if (!ModelState.IsValid)
            {
                model.Genders = await GetGenders();
                model.Relationships = await GetRelationships();

                return View(model);
            }

            await personProfile.CreateAsync(
                model.FirstName,
                model.LastName,
                dateOfBirth,
                model.GenderId,
                model.WantedGenderId,
                model.RelationshipId,
                model.Description,
                User.Id());

            return RedirectToAction("PersonProfileInfo", "Returner");
        }

        [HttpGet]
        public async Task<IActionResult> EditPersonProfile(int id)
        {
            var pp = await personProfile.GetProfileByIdApprovedAsync(id);

            if (pp == null)
            {
                return BadRequest();
            }

            if (pp.DaterId != User.Id())
            {
                return BadRequest();
            }

            var model = new PersonProfileFormModel()
            {
                FirstName = pp.FirstName,
                LastName = pp.LastName,
                DateOfBirth = pp.DateOfBirth.ToString(DateFormat),
                GenderId = pp.GenderId,
                WantedGenderId = pp.WantedGenderId,
                RelationshipId = pp.RelationshipId,
                Description = pp.Description,

            };

            model.Genders = await GetGenders();
            model.Relationships = await GetRelationships();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditPersonProfile(PersonProfileFormModel model, int id)
        {
            var pp = await personProfile.GetProfileByIdApprovedAsync(id);

            if (pp == null)
            {
                return BadRequest();
            }

            if (pp.DaterId != User.Id())
            {
                return BadRequest();
            }

            DateTime dateOfBirth = DateTime.Now;

            if (!DateTime.TryParseExact(
                model.DateOfBirth,
                ValidationConstants.DateFormat,
                CultureInfo.InvariantCulture,
                DateTimeStyles.None,
                out dateOfBirth))
            {
                ModelState.AddModelError(nameof(model.DateOfBirth), $"Invalid date! Format must be: {ValidationConstants.DateFormat}");
            }

            if (!ModelState.IsValid)
            {
                model.Genders = await GetGenders();
                model.Relationships = await GetRelationships();

                return View(model);
            }

            await personProfile.EditAsync(id, model, dateOfBirth);

            return RedirectToAction(nameof(CreatePersonProfile));
        }

        [HttpGet]
        public async Task<IActionResult> DeletePersonProfile(int id)
        {
            var pp = await personProfile.GetProfileByIdApprovedAsync(id);

            if (pp == null)
            {
                return BadRequest();
            }

            if (pp.DaterId != User.Id())
            {
                return BadRequest();
            }

            var model = await personProfile.GetDeleteInfoAsync(id);

            if (model == null)
            {
                return BadRequest();
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> DeletePersonProfileConfirmed(int id)
        {
            var pp = await personProfile.GetProfileByIdApprovedAsync(id);

            if (pp == null)
            {
                return BadRequest();
            }

            if (pp.DaterId != User.Id())
            {
                return BadRequest();
            }

            await sharedService.DeletePersonProfileAsync(id);

            TempData[UserMessageError] = "Dating profile deleted!";

            return RedirectToAction(nameof(CreatePersonProfile));
        }

        private async Task<IEnumerable<GenderViewModel>> GetGenders()
        {
            return await personProfile.AllGenders();
        }

        private async Task<IEnumerable<RelationshipViewModel>> GetRelationships()
        {
            return await personProfile.AllRelationships();
        }
    }
}

Heartify/Heartify/Controllers/ReturnerController.cs
using Heartify.Core.Contracts;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Heartify.Controllers
{
    public class ReturnerController : BaseController
    {
        private readonly IPersonProfileService personProfile;
        private readonly ISharedService sharedService;

        public ReturnerController(IPersonProfileService _personProfile, ISharedService _sharedService)
        {
            personProfile = _personProfile;
            sharedService = _sharedService;
        }

        public async Task<IActionResult> PersonProfileInfo()
        {
            if (await sharedService.ExistsByIdApprovedAsync(User.Id()))
            {
                var model = await personProfile.GetPersonProfileInfoAsync(User.Id());

                return View(model);
            }

            return RedirectToAction(nameof(WaitingForReview));
        }

        public IActionResult WaitingForReview()
        {
            return View();
        }
    }
}

Heartify/Heartify/Views/Returner/PersonProfileInfo.cshtml
@model PersonProfileInfoViewModel

@{
    ViewData["Title"] = "Person Profile Info";
}

<link rel="stylesheet" href="~/css/styles-base.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/view-person-profile-styles.css" asp-append-version="true" />

<main>
    <section>
        <article>
            <div class="my-container">
                <h4>Name: @Model.FirstName @Model.LastName</h4>

                <hr class="inbetween-form">

                <h5>Gender: @Model.Gender</h5>
                <h5>Wanted Gender: @Model.WantedGender</h5>

                <hr class="inbetween-form">

                <h5>Looking for a(n): @Model.Relationship</h5>
                <h5>Date of birth: @Model.DateOfBirth</h5>

                <hr class="inbetween-form">

                <p>Description: @Model.Description</p>

                <hr class="inbetween-form">

                <div class="buttons">
                    <a asp-area="" asp-controller="PersonProfile" asp-action="EditPersonProfile" asp-route-id="@Model.Id" class="button">Edit</a>
                    <a asp-area="" asp-controller="PersonProfile" asp-action="DeletePersonProfile" asp-route-id="@Model.Id" class="button">Delete</a>
                </div>
            </div>
        </article>
    </section>
</main>

Heartify/Heartify/Views/Returner/WaitingForReview.cshtml
@{
    ViewData["Title"] = "Waiting for Review";
}

<link rel="stylesheet" href="~/css/styles-base.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/view-person-profile-styles.css" asp-append-version="true" />

<main>
    <section>
        <article>
            <div class="my-container">
                <h2>Waiting for profile to be reviewed by administrator!</h2>

                <hr class="inbetween-form">
            </div>
        </article>
    </section>
</main>